phone: "+084 822 2208 98"
mail: "Bhhoang1998@gmail.com"
skype: "shinigami_220898"
location: "https://inuvcuon.vn/images/2018/08/voi-nhung-cong-cu-rat-huu-ich-ban-da-co-the-in-truc-tiep-ngay-tren-google-map.jpg"
img_little_about_us: "https://live.staticflickr.com/2474/3884195824_0fcd9fc1c7_b.jpg"
img_list_room_item: "https://images.adsttc.com/media/images/5bbf/eabb/f197/ccec/bc00/03fd/slideshow/800_6652_post_HR.jpg?1539304112"
client: 320
staff: 50
room: 24
award: 12
